#!/usr/bin/python3
import re

line = 'show BaseModel 49faff9a-6318-451f-87b6-910505c55907'
line_pattern1 = r'^(\w+)\s(?:(\S+))\s(\w+\s?\w+)\s("\w+\s?\w+")$'
line_pattern2 = r'^(\S+)(?:\s(\S+)(?:\s(\S+)(?:\s((?:"[^"]*")|(?:(\S)+)))?)?)?'

m = re.search(line_pattern2, line)
if m is None:
    print("none found")
else:
    name = m.group(1)
    class_name = m.group(2)
    id = m.group(3)
    print (type(m.group()))
    print ("----")
    print(f"{name}")
    print(f"{class_name}")
    print(f"{id}")
